<a href="https://colab.research.google.com/github/Mohsi777999/Machine-Learning-Labs/blob/main/Lab_01_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [59]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

Task 1

In [60]:
# load dataset
df = sns.load_dataset("titanic")
print("First 10 rows of the Titanic dataset:")
display(df.head(10))

# check missing values
print("Missing values in each column:")
print(df.isnull().sum())

# fill missing age with mean
mean_age = df["age"].mean()
df["age"] = df["age"].fillna(mean_age)
print("Missing Age values after filling:", df["age"].isnull().sum())

# drop rows where embarked is missing
df = df.dropna(subset=["embarked"])
print("Missing Embarked values after dropping:", df["embarked"].isnull().sum())

First 10 rows of the Titanic dataset:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

Missing values in each column:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
Missing Age values after filling: 0
Missing Embarked values after dropping: 0

Task 2

In [61]:
# Convert Sex Column into numerical values
df["sex"] = df["sex"].map({
    "male": 0,
    "female": 1
})

print("Encoded Sex:")
print(df["sex"].head(10))

# One-Hot Encoding for Embarked
df = pd.get_dummies(
    df,
    columns=["embarked"],
    prefix="Embarked",
    dtype=int
)

print("One-Hot Encoded Embarked:")
print(df[[
    "Embarked_C",
    "Embarked_Q",
    "Embarked_S"
]].head(10))

Encoded Sex:
0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: sex, dtype: int64
One-Hot Encoded Embarked:
   Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           0           1
3           0           0           1
4           0           0           1
5           0           1           0
6           0           0           1
7           0           0           1
8           0           0           1
9           1           0           0

Task 3

In [62]:
X = df[["age", "fare", "sex", "pclass"]]
print("Selected Features:")
display(X.head(10))

# Target variable
y = df["survived"]
print("Target:")
display(y.head(10))

# StandardScaler Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert back to DataFrame for easier viewing
X_scaled = pd.DataFrame(
    X_scaled,
    columns=["Age", "Fare", "Sex", "Pclass"]
)
print("Scaled Features:")
display(X_scaled.head(10))

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.20,
    random_state=42
)

print("Dataset Split Results:")
print("Training features:", X_train.shape)
print("Testing features :", X_test.shape)
print("Training target  :", y_train.shape)
print("Testing target   :", y_test.shape)

print("\nTraining Data:")
display(X_train.head())
print("\nTesting Data:")
display(X_test.head())

Selected Features:

         age     fare  sex  pclass
0  22.000000   7.2500    0       3
1  38.000000  71.2833    1       1
2  26.000000   7.9250    1       3
3  35.000000  53.1000    1       1
4  35.000000   8.0500    0       3
5  29.699118   8.4583    0       3
6  54.000000  51.8625    0       1
7   2.000000  21.0750    0       3
8  27.000000  11.1333    1       3
9  14.000000  30.0708    1       2

Target:

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: survived, dtype: int64

Scaled Features:

        Age      Fare       Sex    Pclass
0 -0.590495 -0.500240 -0.735342  0.825209
1  0.643971  0.788947  1.359911 -1.572211
2 -0.281878 -0.486650  1.359911  0.825209
3  0.412509  0.422861  1.359911 -1.572211
4  0.412509 -0.484133 -0.735342  0.825209
5  0.003524 -0.475913 -0.735342  0.825209
6  1.878437  0.397946 -0.735342 -1.572211
7 -2.133577 -0.221900 -0.735342  0.825209
8 -0.204724 -0.422057  1.359911  0.825209
9 -1.207728 -0.040787  1.359911 -0.373501

Dataset Split Results:
Training features: (711, 4)
Testing features : (178, 4)
Training target  : (711,)
Testing target   : (178,)

Training Data:

          Age      Fare       Sex    Pclass
707 -0.590495  2.404961  1.359911 -1.572211
239  0.003524 -0.355197  1.359911  0.825209
381  0.181046 -0.486650 -0.735342  0.825209
791  0.003524  0.754050  1.359911  0.825209
682 -1.207728  0.298036 -0.735342  0.825209

Testing Data:

          Age      Fare       Sex    Pclass
280 -0.127570 -0.488075 -0.735342  0.825209
434 -1.207728  1.769763  1.359911 -1.572211
39  -1.207728 -0.419875  1.359911  0.825209
417  0.026738 -0.384475 -0.735342 -0.373501
584 -0.899111  0.957394  1.359911 -1.572211